program ascii(output);
{By: Neel Patel}
{Started: November 25 2011}
{Last edited:November 29 2011}
uses crt;

begin
textmode(259);
clrScr;
textbackground(white);
textcolor(red);
writeln('                                  .., ' );
writeln('                               ...@@@@..');
writeln('                              ..@@@@@@@@@.');
writeln('                              ..@@@@@@@@@@.');
writeln('                      ..........@@@@@@@@@@@.');
writeln('                    ..@@@@@@@@@@..@@@@@@@@@@.');
writeln('                   ..@@@@@@@@@@@@@@..@@@@@@@@@.');
writeln('                   ..:@@@@@@@@@@@@@@@@..@@@@@@.');
writeln('                          ....,@@@@@@@@@@@@@@@@.');
writeln('                        ..,@@@@@@@@@@@@@@@@@@@@@@...');
writeln('                       ..@@@@@@@@@@@@@@@@@@@@@@@@@@@@..');
writeln('                   ..::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..');
writeln('                  ...:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..');
writeln('                 ..:::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..');
writeln('                ..:::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.');
writeln('               ..::::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..');
writeln('              ..::::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.,');

write('             ..:::::@@@@@@@@@@@@@@@@@');
textcolor(black); write('..');
textcolor(red);writeln('@@@@@@@@@@@@@@@@@@@@@@@');


write('            ..::::::@@@@@@@@@@@@@@@@');
textcolor(black);write('.....');
textcolor(red);write('@@@@@@@@@@@@@@@@@@@');
textcolor(black);write('..');
textcolor(red);writeln('..');


write('            .::::::@@@@@@@@@@@@@@@@');
textcolor(white);write('........');
textcolor(red);write('@@@@@@@@@@@@@@@');
textcolor(white);write('....:');
textcolor(red);writeln('~.');


write('           .,::::::@@@@@@@@@@@@@@@@');
textcolor(white);write('..........');
textcolor(red);write(':@@@@@@@@@');
textcolor(white);write('........');
textcolor(red);writeln('~.');


write('          ..:::::::@@@@@@@@@@@@@@@@@@');
textcolor(white);write(',..........');
textcolor(red);write('@@@@');
textcolor(white);write('..........:');
textcolor(red);writeln('@@:.');


write('         ..:::::::@@@@@@@@@@@@@@@@@@::777');
textcolor(white);write('.................');
textcolor(red);writeln(':@@@@@.');



write('         ..::::::::@@@@@@@@@@@@@@@@@:.I       +');
textcolor(white);write('.......');
textcolor(red);writeln('7    .::@@@.');


write('        ..::::::::~~~~~~~~::::~~~~::.I   ');
textcolor(black);write('/~\   I..I   @');
textcolor(red);writeln('   ::~~~..');


write('        ..::::::::~~~~~~~~:::::~~:::.II  ');
textcolor(white);write('\_/~');
textcolor(red);writeln('   .,II     .....::~~..');

write('        ..::::::::~~~~~~~~:::::~~::::.I=.......');
textcolor(yellow);write('=+++..');
textcolor(red);writeln(' .::::::~~..');


write('         ..:::::::::::::~~~:::::~~::::,:::::..');
textcolor(yellow);write('++++++++,.');
textcolor(red);writeln(':::::::~~.:');


write('          :.:::::::::::::~~~:::::~~::::::::');
textcolor(yellow);write(',.+++++++++++++');
textcolor(red);writeln('.:::::~~');


write('          .:::::::::,::::~~:::::~~~::::::');
textcolor(yellow);write('.++++++++++++++++..');
textcolor(red);writeln(':~~~..');


write('          ..:::::::::,::~~~~~~~~~~~~~+++');
textcolor(yellow);write('.+++++++++++++++++++.');
textcolor(red);writeln('~~~..');


write('           .::::::::::::~~~~~~');
textcolor(white);write('?????????,');
textcolor(yellow);write('....+++++++++++++++++.');
textcolor(red);writeln('~..');


write('           ..::::::::::::');
textcolor(white);write('~?????????????=');
textcolor(yellow);write('.    +........:++++++.');
textcolor(red);writeln(':.');


write('             .::::::::::');
textcolor(white);write('????????????????');
textcolor(yellow);write('....++++++++++++...++');
textcolor(red);writeln('...');


write('              ...::::::');
textcolor(white);write('????????????????????');
textcolor(yellow);write('..++++++++++.');
textcolor(red);writeln('~~~~~..');



write('                ...;::');
textcolor(white);write('????????????????????????');
textcolor(yellow);write('..=++++~');
textcolor(red);writeln('.??~~~~.');


write('                 ...???????????????????????????');
textcolor(yellow);write('....');
textcolor(red);writeln('?????:...');

writeln('                  ..???????????????????????????????+...');
writeln('                     ..,????????????????????????:....');
writeln('                       ......????????????~.......');

readln
end.