program Name (output);
uses crt;

begin
     clrScr;

     writeln(' NN     NN   EEEEEEEE   EEEEEEEE  LL      ');
     writeln(' NNN    NN   EE         EE        LL      ');
     writeln(' NN N   NN   EE         EE        LL      ');
     writeln(' NN  N  NN   EEEEEEEE   EEEEEEEE  LL      ');
     writeln(' NN   N NN   EE         EE        LL      ');
     writeln(' NN    NNN   EE         EE        LL      ');
     writeln(' NN     NN   EEEEEEEE   EEEEEEEE  LLLLLLL ');
     writeln;
     writeln;
     writeln;
     writeln(' PPPPPP    AAAA   TTTTTTTT EEEEEEE LL     ');
     writeln(' PP    P AA    AA    TT    EE      LL     ');
     writeln(' PP    P AA    AA    TT    EE      LL     ');
     writeln(' PPpppp  AAAAAAAA    TT    EEEE    LL     ');
     writeln(' PP      AA    AA    TT    EE      LL     ');
     writeln(' PP      AA    AA    TT    EE      LL     ');
     writeln(' PP      AA    AA    TT    EEEEEEE LLLLLL ');




readln
end.




