program DotMatrix;
uses crt;

{This is from Page 44 qusetion 11}

begin
ClrScr;

writeln;
writeln(' Number 7 ');
writeln;
writeln(' ..... ');
writeln(' .   . ');
writeln('    .  ');
writeln('   .   ');
writeln('  .    ');
writeln('  .    ');
writeln('  .    ');

writeln;
writeln;
writeln(' Lowercase Greek Letter "pi"');
writeln;

writeln('');
writeln('');
writeln('');
writeln(' ..... ');
writeln('  . .  ');
writeln('  . .  ');
writeln(' .   .  ');
readln

end.