program population (output);
uses crt;

var
Population:real;
{SYear:integer;
EYear:integer;}
Year:integer;
Rate:real;


begin
{writeln('Enter your start year and end year');
write('Start year: '); readln(SYear);
write('End year  : '); readln(Eyear);

writeln('Enter rate of growth of population PER YEAR');
readln(Rate);

writeln('Enter Current Population'); }

for Year:= 1987 to 2087 do
  begin
    Current population:= 5.0 *
