program ascii(output);
{By: Neel Patel}
{Started: November 25 2011}
{Last edited:November 29 2011}
uses crt;

begin
textmode(259);
clrScr;

textcolor(red);
writeln('                                  ..,                               ');
writeln('                               ...@@@@..                            ');
writeln('                              ..@@@@@@@@@.                          ');
writeln('                              ..@@@@@@@@@@.                         ');
writeln('                      ..........@@@@@@@@@@@.                        ');
writeln('                    ..@@@@@@@@@@..@@@@@@@@@@.                       ');
writeln('                   ..@@@@@@@@@@@@@@..@@@@@@@@@.                     ');
writeln('                   ..:@@@@@@@@@@@@@@@@..@@@@@@.                     ');
writeln('                          ....,@@@@@@@@@@@@@@@@.                    ');
writeln('                        ..,@@@@@@@@@@@@@@@@@@@@@@...                ');
writeln('                       ..@@@@@@@@@@@@@@@@@@@@@@@@@@@@..             ');
writeln('                   ..::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..             ');
writeln('                  ...:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..          ');
writeln('                 ..:::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..         ');
writeln('                ..:::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.        ');
writeln('               ..::::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@..      ');
writeln('              ..::::@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.,     ');



write('             ..:::::@@@@@@@@@@@@@@@@@');
textcolor(white); write('..');
textcolor(red);writeln('@@@@@@@@@@@@@@@@@@@@@@@      ');


write('            ..::::::@@@@@@@@@@@@@@@@');
textcolor(white);write('.....');
textcolor(red);write('@@@@@@@@@@@@@@@@@@@');
textcolor(white);write('..');
textcolor(red);writeln('..   ');


write('            .::::::@@@@@@@@@@@@@@@@');
textcolor(white);write('........');
textcolor(red);write('@@@@@@@@@@@@@@@');
textcolor(white);write('....:');
textcolor(red);writeln('~. ');


write('           .,::::::@@@@@@@@@@@@@@@@');
textcolor(white);write('..........');
textcolor(red);write(':@@@@@@@@@');
textcolor(white);write('........');
textcolor(red);writeln('~.   ');


write('          ..:::::::@@@@@@@@@@@@@@@@@@');
textcolor(white);write(',..........');
textcolor(red);write('@@@@');
textcolor(white);write('..........:');
textcolor(red);writeln('@@:.   ');


write('         ..:::::::@@@@@@@@@@@@@@@@@@::777');
textcolor(white);write('.................');
textcolor(red);writeln(':@@@@@..   ');



write('         ..::::::::@@@@@@@@@@@@@@@@@:.I       +');
textcolor(white);write('......');
textcolor(red);writeln('7    .::@@@.   ');


write('        ..::::::::@@@@@@@@::::@@@@::.I   ');
textcolor(white);write('/~\    ....  O');
textcolor(red);writeln('   ::@@@@@...');


write('        ..::::::::@@@@@@@@:::::@@:::.II  ');
textcolor(white);write('\_/~');
textcolor(red);writeln('   .,II     .....::@@..');

write('        ..::::::::@@@@@@@@:::::@@::::.I=.......');
textcolor(yellow);write('=+++..');
textcolor(red);writeln(' .::::::@@..');


write('         ..:::::::::::::@@@:::::@@::::,:::::..');
textcolor(yellow);write('++++++++,.');
textcolor(red);writeln(':::::::@@.:');


write('          :.:::::::::::::@@:::::@@::::::::');
textcolor(yellow);write(',.+++++++++++++');
textcolor(red);writeln('.:::::@@');


write('          .:::::::::,::::@@:::::@@@::::::');
textcolor(yellow);write('.++++++++++++++++..');
textcolor(red);writeln(':@@@..');


write('          ..:::::::::,::@@@@@@@@@@@@@+++');
textcolor(yellow);write('.+++++++++++++++++++.');
textcolor(red);writeln('@@@..');


write('           .::::::::::::~~~~~~');
textcolor(white);write('?????????,');
textcolor(yellow);write('....+++++++++++++++++.');
textcolor(red);writeln('~..');


write('           ..::::::::::::');
textcolor(white);write('~?????????????=');
textcolor(yellow);write('.   +........:++++++.');
textcolor(red);writeln(':.');


write('             .::::::::::');
textcolor(white);write('????????????????');
textcolor(yellow);write('....++++++++++++...++');
textcolor(red);writeln('...');


write('              ...::::::');
textcolor(white);write('????????????????????');
textcolor(yellow);write('..++++++++++.');
textcolor(red);writeln('~~~~~..');



write('                ...;::');
textcolor(white);write('????????????????????????');
textcolor(yellow);write('..=++++~');
textcolor(red);writeln('.??~~~~.');


write('                 ...');
textcolor(white);write('???????????????????????????');
textcolor(yellow);write('....');
textcolor(red);writeln('?????:...');


write('                  ..');
textcolor(white);write('???????????????????????????????');
textcolor(red);writeln('+...');


write('                     ..,');
textcolor(white);write('????????????????????????');
textcolor(red);writeln(':....');


write('                       ......');
textcolor(white);write('????????????~');
textcolor(red);writeln('.......');

writeln('');
writeln('Angry-brids');
writeln('Copyright of Rovio');
writeln('Created using a website, modified many characters ~ ---> @ ');
writeln('Neel Patel - 9B');

readln
end.